### ISSUE TITLE
Gather sntemp/prms segment/catchment attributes

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#12]
For a first crack, I think we should try the model with just the sntemp/prms segment/catchment data. Then we can add NHD/streamcat data later on. So we will need to "gather" this data. 

I'm not sure exactly how best to do this. It's part of the delaware_model_prep pipeline, but 
1. it's not fully integrated into that pipeline yet
2. i don't know the best way to leverage that. Maybe we just say: "this is where we got it" and leave it at that, trusting the other pipeline.

**Comment by lekoenig** [comment]
This plan to first work with prms reach/catchment data sounds good to me, @jsadler2. I'll look into the delaware-model-prep pipeline and might pitch this question about integrating across pipelines to the ds-pipelines function channel.

**Comment by lekoenig** [comment]
> I'm not sure exactly how best to do this. It's part of the delaware_model_prep pipeline, but 
> 1. it's not fully integrated into that pipeline yet
> 2. i don't know the best way to leverage that. Maybe we just say: "this is where we got it" and leave it at that, trusting the other pipeline.

It does seem like to the extent USGS-R projects have linked pipelines in the past, approach 2 is the route that's been used before. I'm happy with that. Do you know, @jsadler2, if there is a plan to publish these products in a data release, or how likely these files are to changes (that we would have to monitor manually)?
