### ISSUE TITLE
subset sntemp/prms network to just "Lower Delaware"

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#13]
We will need to subset the full DRB sntemp/prms network to just the "Lower Delaware."

**Comment by lekoenig** [comment]
I've been thinking about this with respect to some of the other input datasets. For now, we're gathering DO data for the full DRB - do you have any thoughts on whether we should subset those? Or perhaps we'll want to take advantage of additional data for model training?
