### ISSUE TITLE
container difficulties with S3/streamMetabolizer

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#138]
I've run into a snag with the container.

In v0.2, I am running targets version 0.10. The way this version of targets interfaces with S3 in an outdated way, so I updated to targets version 0.12 in v0.3 of the container. For some reason, however, when I install streamMetabolizer in v0.3 of the container, streamMetabolizer installs version 0.9.3. In v0.2, streamMetabolizer is 0.12.0.

**Comment by lekoenig** [comment]
When building the container can you pass along additional arguments? e.g. install using 

```
devtools::install_github("USGS-R/streamMetabolizer/@v0.12.0")
```

instead of 

```
devtools::install_github("USGS-R/streamMetabolizer")
```
