### ISSUE TITLE
Issues running pipeline with new nhd functionality

### ISSUE THREAD

**Issue by galengorski** [USGS-R/drb-do-ml#142]
I am trying to run the pipeline, when I run `tar_make(p2a_well_obs_sites)` to create the modeling input data, I run into the following error: 
![image](https://user-images.githubusercontent.com/32860978/176516451-5da16537-bea8-4625-8ed7-4040ec965254.png)
 
it looks like the function `match_site_ids_to_segs` within the target `p2a_seg_attr_w_sites` is looking for a column named "segidnat" and not finding it. When I run `tar_load(p2_sites_w_segs)` and look at the column names of the tibble, I also don't see the "segidnat" column, I'm wondering if the column name didn't get updated, or maybe I am thinking about it wrong. Let me know what you think when you get a chance @lekoenig 

PS I am running this on tallgrass, but I was able to replicate the error running on my local machine too

**Comment by lekoenig** [comment]
Thanks for pointing this out - I get the same error! None of the targets in 2a_model have been updated to reflect the change from the NHM fabric (with reach identifier `segidnat`) to NHDPlusv2 (with reach identifier `COMID`). I'll push a PR shortly that includes those changes.
