### ISSUE TITLE
modify functional performance to accommodate replicates

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#162]
We need to make the functional performance code accommodate multiple replicates. It would also be nice to specify which models to do the calculations for.

**Comment by lekoenig** [comment]
@galengorski, can this issue be closed (i.e., has it been addressed in #156)?

**Comment by galengorski** [comment]
I wanted to leave this issue open as #156 only runs for a single replicate now. The next step with these scripts will be: 1) integrating into the pipeline and 2) accommodating multiple replicates for each model run

**Comment by jsadler2** [comment]
this was addressed in #182
