### ISSUE TITLE
Python plotting scripts

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#184]
I have some plotting scripts that I've been using.
Some of these are substitutes to the R functionality #180.

I'm not sure the best way forward.
I'm much more comfortable in Python.
You guys are more comfortable in R. 
Eventually we will need to decide on one or the other for the manuscript figures, but I think for now it can make sense to just keep doing what we are comfortable with.

**Comment by galengorski** [comment]
Just to chime in, for the estuary salinity paper, I have figures from both python and R in the manuscript. I've edited them to look similar, but for me, that was easier than deciding on one plotting language. [Here is a link to the figures](https://doimspp.sharepoint.com/:w:/s/usgs-GS-WMA-IWP-PUMP/EV1jDKLleM1NnA1zQ6n6eNEBbhzO85drwJxSMPXorlXbVw?e=GKQM2O) if you want to take a look, some had to be slightly edited in illustrator. Just an option if we want to punt on this decision...

**Comment by jsadler2** [comment]
Thanks, Galen. That's helpful to know that that is the direction you all took and it worked out okay

**Comment by lekoenig** [comment]
> I have some plotting scripts that I've been using.
> Some of these are substitutes to the R functionality https://github.com/USGS-R/drb-do-ml/issues/180.

There are a few ways to slice the data in this pipeline (e.g. partition/model id/site id/etc). So to a certain extent, in this semi-exploratory phase I actually think it's a nice gut-check that we've drafted the same type of figure independently and get the same results/draw the same conclusions 🙂 

If there are figures that we commonly refer to, I think it's worth checking the code that creates them into version control, even if not formally integrated in either the `targets` or `snakemake` parts of the pipeline. Once we decide on the set of figures we want for the manuscript, we can add those into the pipeline (R or python probably depending on who creates the publication-quality version of each figure). Just my 2 cents.
