### ISSUE TITLE
Training start date on calendar year

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#204]
I noticed today that the training start date is at the beginning of the _calendar_ year, not the _water_ year. Seems like it should be the _water year_

https://github.com/USGS-R/drb-do-ml/blob/43b4277f0fe3ae4d3f61dc8bb48ed5a78b36f456/_targets.R#L91

**Comment by jsadler2** [comment]
I'm guessing it doesn't make too much of a difference, but I think it would be good to correct this.

**Comment by lekoenig** [comment]
Good point, I have a vague recollection that this date `1980-01-01` is when gridMET data are available. I would have to check if that's true, but could explain why we chose the calendar date start.
