### ISSUE TITLE
Omit WQP targets

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-do-ml#205]
If we're not using the discrete data, we should simplify the pipeline and omit the WQP-related targets (they'll still be in the commit history if we want to restore them at some point down the line). Here are the objects/targets related to WQP data:

`wqp_vars_select`
`CharNames_select`
`params_select`
`units_select`
`omit_wqp_events`
`p1_wqp_data_file`
`p1_wqp_data`
`p2_filtered_wqp_data`
`p2_filtered_wqp_data_subset`
`p2_wqp_ind_csv`
`p3_wqp_report`

Does this sound OK to you, @jsadler2?

**Comment by jsadler2** [comment]
Sounds good to me!
