### ISSUE TITLE
multiple DO values per timestep at one site

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#22]
I was trying to visualize the DO data and I ran across this quirk. There are 8 time steps for site `01467200` that have two values each:
![image](https://user-images.githubusercontent.com/6943441/144096995-a53f26dc-13b1-4743-bf14-ddc6a63b9441.png)

**Comment by jsadler2** [comment]
I'm not sure why this would be the case. It's also a little odd that values are different at the same time. Anyway, I'm not sure if this is actually consequential if we are aggregating up to a daily time step anyway, but I wanted to document it.

**Comment by lekoenig** [comment]
Thanks for pointing this out, Jeff! I'll make a note to double-check this site, but I'm very confident this is a daylight savings time issue. I've updated the code to use "UTC" time for the instantaneous data instead of local time for this reason. We can still use local time to perform computations such as daily aggregations.

**Comment by jsadler2** [comment]
Ohhh. Good call! I hadn't thought of daylight savings:
![image](https://user-images.githubusercontent.com/6943441/144104516-8889f455-3459-44e4-8b34-0da998bf945b.png)

**Comment by jsadler2** [comment]
Strange that it shows up only at that one site.

Okay. Good to know about UTC time. So does that mean we'll have to convert back to local time to do the daily aggregations?

**Comment by lekoenig** [comment]
I took a closer look at this site and as expected, the duplicated timestamps are related to daylight savings time (although I've been trying to figure out why the timestamps you show occur between 5:00A - 6:00A. I expect the duplicated timestamps to show up between 1:00A-2:00A. It looks like `dateTime` is being displayed in UTC (EDT = UTC+4, EST = UTC+5), but I can't reproduce that on my end right now). 

This [site](https://waterdata.usgs.gov/nwis/uv?site_no=01467200) is unique in that they had two sensors co-deployed during this time. My understanding is that between sensor/location swaps, instruments might be co-deployed for some time to ensure comparability. The old sonde (`Value_Inst`) records every 15 minutes and the new sonde (`..barge..`) records every 5 minutes. Something funky is happening here when we call local time in `dataRetrieval::readNWISuv()` that is resulting in the new sonde values being repeated for the 1:00 EDT and 1:00 EST timestamps. Here's what the raw data look like:

![Inkedduplicated_timestamps_edit](https://user-images.githubusercontent.com/8785034/144322914-45cb0ef3-4c7c-46fe-83f1-5a9dd997c64d.jpg)

I wonder if this is related to time zone conversion quirks, or even how clock times were set/tracked on the two sensors. However, if we use UTC which is the default time zone for storage (and in dataRetrieval), we don't see any duplicated timestamps and we get what is reflected in the data displayed on the [NWIS page](https://nwis.waterdata.usgs.gov/usa/nwis/uv/?cb_00300=on&cb_00300=on&format=html&site_no=01467200&period=&begin_date=2020-11-01&end_date=2020-11-01) for this site:

![duplicated_timestamps_utc](https://user-images.githubusercontent.com/8785034/144321998-b1f6af4f-9985-4651-a811-755f70134349.png)

 In `get_inst_nwis_data.R` we preferentially select data from the new sonde when it is available:

`"01467200" = site_data %>%
          mutate(Value_Inst_merged = coalesce(ISM.Test.Bed...ISM.Test.Bed..barge.._Value_Inst,Value_Inst),
                 Value_Inst_cd_merged = coalesce(ISM.Test.Bed...ISM.Test.Bed..barge.._Value_Inst_cd,Value_Inst_cd))`

Using UTC, our output looks like this:

![save_out](https://user-images.githubusercontent.com/8785034/144322271-d8457008-c57d-499d-96f8-5cc8f565dc5b.png)

So I think using UTC for sub-daily data is the way to go, although I'll want to keep an eye on time zones used by other data sources. For the daily summaries I suggest we can still convert to local time prior to aggregating.
