### ISSUE TITLE
make `omit_nwis_sites` a target

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#30]
Currently the `omit_nwis_sites` is a character vector that is defined in `_targets.R`. The problem with this is that if/when we update this vector, `targets` doesn't recognize that a "dependency" has changed. That is because it's not a `targets::tar_target`. So I think it would be best to define it as it's own target. This is how Jake & Co. approached similar situations in the temp forecasting pipelines. 

cc @jds485  - we'll need to think about this for the salinity pipeline too

**Comment by lekoenig** [comment]
I didn't realize that, thanks for pointing this out, @jsadler2. We're currently using `omit_nwis_sites` in DO and inland-salinity to omit tidal sites that are coded as "ST" in NWIS.

**Comment by jds485** [comment]
Are you sure? I just tested what changing that vector of values would do and it looks like it's picked up as a change 
![image](https://user-images.githubusercontent.com/8761242/146599143-c9480ce1-9168-47ad-9aa0-d2d3924e8efe.png)

**Comment by jsadler2** [comment]
hmm. I'm not sure. I thought that's the behavior I noticed, but let me double check.

Always keeping us honest, @jds485 ! 😄

**Comment by jds485** [comment]
haha, that's what reviewers are for!

**Comment by jsadler2** [comment]
I stand corrected! Good catch, @jds485
