### ISSUE TITLE
unusual data from site `01482537`

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#31]
I'm getting unusual data from `readNWISuv` for site `01482537` (https://waterdata.usgs.gov/nj/nwis/inventory/?site_no=01482537)

```R
head(dataRetrieval::readNWISuv(siteNumbers = "01482537",parameterCd="00300",startDate = "",endDate = "",tz = "UTC") %>% 
    dataRetrieval::renameNWISColumns(p00300="Value",p00095="Value"))
  agency_cd  site_no            dateTime at.0.5.ft.depth_Value_Inst
1      USGS 01482537 2008-08-06 17:45:00                       13.5
2      USGS 01482537 2008-08-06 18:00:00                       13.3
3      USGS 01482537 2008-08-06 18:15:00                       14.7
4      USGS 01482537 2008-08-06 18:30:00                       14.7
5      USGS 01482537 2008-08-06 18:45:00                       14.8
6      USGS 01482537 2008-08-06 19:00:00                       14.5
  at.0.5.ft.depth_Value_Inst_cd at.2.0.ft.depth_Value_Inst
1                             A                         NA
2                             A                        9.6
3                             A                       10.5
4                             A                       10.3
5                             A                       10.6
6                             A                       11.6
  at.2.0.ft.depth_Value_Inst_cd tz_cd
1                          <NA>   UTC
2                             A   UTC
3                             A   UTC
4                             A   UTC
5                             A   UTC
6                             A   UTC
```

I think it has something to do with the `at.0.5.ft.depth_Value_Inst` column names and that throws off some downstream processes.

For reference. When I do a different site (`01472104`) I get this:
```R
head(dataRetrieval::readNWISuv(siteNumbers = "01472104",parameterCd="00300",startDate = "",endDate = "",tz = "UTC") %>%
     dataRetrieval::renameNWISColumns(p00300="Value",p00095="Value"))
  agency_cd  site_no            dateTime Value_Inst Value_Inst_cd tz_cd
1      USGS 01472104 2007-10-01 05:00:00        6.9             A   UTC
2      USGS 01472104 2007-10-01 06:00:00        6.7             A   UTC
3      USGS 01472104 2007-10-01 07:00:00        6.6             A   UTC
4      USGS 01472104 2007-10-01 08:00:00        6.5             A   UTC
5      USGS 01472104 2007-10-01 09:00:00        6.5             A   UTC
6      USGS 01472104 2007-10-01 10:00:00        6.5             A   UTC
```

Then the columns are `Value_Inst`.

**Comment by jsadler2** [comment]
I am curious about why this is showing up now and I didn't seem to have this problem in earlier builds. I'm also curious as to why it's happening in the first place. 

But overall I'm also thinking that it's not worth spending a whole ton of time/effort on since it seems like an isolated case and this site has only 57 observations. 

So, for now, I'm in favor of just omitting this site.

**Comment by lekoenig** [comment]
lol this is a whole thing (and is why we had to update the helper functions in inland-salinity earlier this week), see [Teams](https://teams.microsoft.com/l/message/19:264c78fefa624bcfaf46ac10b9305f5e@thread.skype/1639492810490?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&groupId=2651eb2e-8cf1-4caa-a084-0a11facc1d36&parentMessageId=1639492810490&teamName=GS-WMA%20IIDD%20Staff&channelName=Function%20-%20Data%20Pipelines&createdTime=1639492810490) discussion.

**Comment by lekoenig** [comment]
I'll link to this issue when I submit the code-update PRs that bring in recent updates from inland-salinity.
