### ISSUE TITLE
Evaluate the utility of adding more sites 

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-do-ml#49]
In our baseline LSTM model, we filter for sites with at least 300 DO observation-days, resulting in 13 sites in the Lower DRB. We could think about whether it's worth adjusting this criteria so that we have more sites to work with. There's probably a tradeoff between having more information at a site versus having more sites but with potentially less information at any given site - but that also seems like a potentially interesting modeling question. 

Some gut-check steps might include:

- How many sites do we gain by changing the criteria to 200 days? 100 days?
- Our static and dynamic features are aggregated at the scale of PRMS segments, so how many new (unique) PRMS segments do we gain by changing the criteria to 200 days? 100 days?

**Comment by lekoenig** [comment]
As a first cut, I looked at the number of unique sites and PRMS segments gained by lowering the observation-day criteria:

- 300 days (current): results in 13 well-observed sites represented by 10 unique PRMS segments
- 200 days: results in 15 well-observed sites situated across 11 unique PRMS segments
- 100 days: results in 22 well-observed sites situated across 18 unique PRMS segments

**Comment by galengorski** [comment]
The idea of lowering the threshold for site inclusion makes sense to me, especially because the model is having the most trouble extrapolating over space. To me this suggests that adding in a diversity of sites (even if they don't have great temporal coverage) might help the model learn different "site dynamics".
