### ISSUE TITLE
why is 01481500 "tidal"?

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#50]
@jsadler2, do you remember how you determined `01481500` is tidal?

_Originally posted by @lekoenig in https://github.com/USGS-R/drb-do-ml/pull/40#discussion_r801115087_

**Comment by jsadler2** [comment]
Huh. I'm glad you brought this up, @lekoenig. When I look at the specific conductance data I'm not seeing a tidal signal after all. I'm not sure why I thought that it was tidal originally, but looking at this, it seems like it's not.
![image](https://user-images.githubusercontent.com/6943441/155412273-ebc2026d-e393-4e28-b17c-32852e27a0f7.png)

**Comment by lekoenig** [comment]
Thanks for taking another look at this site. So are we in agreement to add "01481500" back in the mix?

**Comment by jsadler2** [comment]
I agree
