### ISSUE TITLE
gather metabolism data

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#57]
To explicitly represent metabolism in the model (i.e., to do #56) we will need to gather metabolism data: GPP, ER, and K. Metabolism estimates for 6 sites in our study area (7 if we add back 01481500 (see #50)) are included in the[ Appling et. al data release](https://www.sciencebase.gov/catalog/item/59bff507e4b091459a5e0982). Included in those are our 2 validation sites.

![image](https://user-images.githubusercontent.com/6943441/156815200-14f68c0e-a1dd-4885-b980-f6c135045aaf.png)

**Comment by jsadler2** [comment]
The metabolism estimates are between Fall 2007 and Fall 2016. So really we only have 9 years of metabolism data to work with.

**Comment by lekoenig** [comment]
> Actually there are 602 points on the map and only estimates for 356 points.

My recollection is that 602 reflects the number of sites with DO data, and 356 reflects the number of sites for which metabolic rates could reasonably be modeled. There are more details in the paper that summarizes the dataset: https://www.nature.com/articles/sdata2018292

**Comment by lekoenig** [comment]
The ScienceBase release includes the underlying DO data as well as model diagnostic information. If we want to just download the daily rates, we're interested in this sb_id: https://www.sciencebase.gov/catalog/item/59eb9c0ae4b0026a55ffe389 , which I believe contains all of the 356 sites.

**Comment by jsadler2** [comment]
Ahh. Okay. Thanks, @lekoenig. I was going into the individual model fits (https://www.sciencebase.gov/catalog/item/59eb9ba6e4b0026a55ffe37f). I'm thinking that for our purposes, we can just start with the item you pointed out. It's quite a bit simpler.
