### ISSUE TITLE
Initial catchment attribute data 

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#6]
We need to catalog which catchment attributes we have available in the DRB

**Comment by jsadler2** [comment]
The other big one which has been brought up is streamcat: https://www.epa.gov/national-aquatic-resource-surveys/streamcat-metrics-and-definitions. The catch here is that these are on the NHD reaches where the prepped met data (see https://github.com/USGS-R/drb-do-ml/issues/5#issuecomment-955067932) and adjacency data are on the PRMS reaches.

**Comment by jsadler2** [comment]
Blodgett introduced me to this one: https://www.sciencebase.gov/catalog/item/5669a79ee4b08895842a1d47 which seems similar to streamcat. Not sure if they relate.

**Comment by lekoenig** [comment]
> Blodgett introduced me to this one: https://www.sciencebase.gov/catalog/item/5669a79ee4b08895842a1d47 which seems similar to streamcat. Not sure if they relate.

This dataset looks really useful in that it provides a bunch of covariates processed and paired to NHDV2 flowline reaches (similar to EPA StreamCat). These data would require cross-walk from NHDV2 reaches to PRMS framework, though.
